### ISSUE TITLE
Populate hosts file from inventory

### ISSUE THREAD

**Issue by goetzk** [weareinteractive/ansible-hosts#5]
Hi,
I have a group of hosts I'd like configured in each others hosts file.
I think the sanest way will be to make a task which takes the hosts and builds a list to pass to hosts: ; my question is if you think it would be useful in the role or if it should be handled outside.

thanks,
Karl.

**Comment by franklinkim** [comment]
Hi, while looking at your question I took the opportunity to move and update the role to `weareinteractive.hosts` (2.0.0).

I don't believe it's a role's responsibility to collect multiple sources into one variable since this differs from each env and use case so this would be sth to be handled outside.
